# Generated by Django 4.1.6 on 2023-02-09 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.automovil')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participante.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.automovil')),
            ],
        ),
    ]
